apiVersion: v1
kind: ConfigMap
metadata:
  name: pms-config
  namespace: default
data:
  DB_HOST: "mysql-service"
  DB_PORT: "3306"
  DB_NAME: "helpdesk_db"
  SERVER_PORT: "8081"
  APP_NAME: "helpdesk-ticketing-system"