apiVersion: apps/v1
kind: Deployment
metadata:
  name: pms-deployment
  namespace: default
  labels:
    app: helpdesk-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helpdesk-app
  template:
    metadata:
      labels:
        app: helpdesk-app
    spec:
      containers:
        - name: helpdesk-app
          image: helpdesk-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql-service:3306/helpdesk_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: pms-secret
                  key: DB_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pms-secret
                  key: DB_PASSWORD
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: pms-config
                  key: SERVER_PORT
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 200
            periodSeconds: 30
            failureThreshold: 3